/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.expense_manager;

import javax.swing.*;
import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.nio.file.Files;
import java.nio.file.Paths;

/**
 *
 * @author MrRight
 */
public class expense_form extends javax.swing.JFrame {

        /**
         * Creates new form expense_form
         */
        private List<ExpenseIncome> expenses;
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

        public expense_form() {
                initComponents();
        }

        private void setExpenseTotalText() {
                // Get total expense, income, and balance using ExpenseTotal module
                double expense = ExpenseTotal.getTotalExpense();
                double income = ExpenseTotal.getTotalIncome();
                double balanceValue = ExpenseTotal.getBalance();

                // Set the text of each JTextField with the calculated values
                totalExpense.setText(String.format("%.2f", expense));
                totalncome.setText(String.format("%.2f", income));
                balance.setText(String.format("%.2f", balanceValue));
        }

        public expense_form(List<ExpenseIncome> expenses) {
                // Set the data model of the JTable to null

                this.expenses = expenses != null ? expenses : new ArrayList<>(); // Initialize the expenses list with a
                                                                                 // default
                                                                                 // value if it's null
                initComponents();
                populateExpenseTable(); // Populate the expense table with the initialized expenses list
                setExpenseTotalText();

        }

        private void populateExpenseTable() {
                // Iterate over the list of expenses and add them to the table
                DefaultTableModel model = (DefaultTableModel) expenseTable.getModel();
                for (ExpenseIncome expense : expenses) {
                        model.addRow(new Object[] { dateFormat.format(expense.getDate()), expense.getType(),
                                        expense.getTitle(),
                                        expense.getAmount() });
                }

        }

        double expense = ExpenseTotal.getTotalExpense();
        double income = ExpenseTotal.getTotalIncome();
        double balanceValue = ExpenseTotal.getBalance();

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel5 = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();
                jLabel6 = new javax.swing.JLabel();
                jLabel7 = new javax.swing.JLabel();
                addExpense = new javax.swing.JButton();
                expenseTitle = new javax.swing.JTextField();
                expenseAmount = new javax.swing.JTextField();
                clearExpense = new javax.swing.JButton();
                jLabel11 = new javax.swing.JLabel();
                expenseDate = new com.toedter.calendar.JDateChooser();
                expenseType = new javax.swing.JComboBox<>();
                jLabel17 = new javax.swing.JLabel();
                jPanel6 = new javax.swing.JPanel();
                jLabel15 = new javax.swing.JLabel();
                fromDateChooser = new com.toedter.calendar.JDateChooser();
                jLabel16 = new javax.swing.JLabel();
                toDateChooser = new com.toedter.calendar.JDateChooser();
                jLabel10 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                expenseTable = new javax.swing.JTable();
                searchDate = new javax.swing.JButton();
                jPanel7 = new javax.swing.JPanel();
                jLabel12 = new javax.swing.JLabel();
                jLabel13 = new javax.swing.JLabel();
                jLabel14 = new javax.swing.JLabel();
                totalExpense = new javax.swing.JTextField();
                totalncome = new javax.swing.JTextField();
                balance = new javax.swing.JTextField();
                jLabel18 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

                jLabel5.setBackground(new java.awt.Color(0, 0, 51));
                jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(0, 0, 102));
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("Add Expense/Income");

                jLabel6.setText("Title:");

                jLabel7.setText("Amount:");

                addExpense.setText("Add");
                addExpense.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addExpenseActionPerformed(evt);
                        }
                });

                expenseAmount.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                expenseAmountActionPerformed(evt);
                        }
                });

                clearExpense.setText("Clear");
                clearExpense.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                clearExpenseActionPerformed(evt);
                        }
                });

                jLabel11.setText("Date:");

                expenseType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Income", "Expense" }));
                expenseType.setSelectedIndex(1);

                jLabel17.setText("Type");

                jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                jLabel15.setText("Search from ");

                jLabel16.setText("To");

                jLabel10.setBackground(new java.awt.Color(0, 0, 51));
                jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(0, 0, 102));
                jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel10.setText("Transaction History");

                expenseTable.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {

                                },
                                new String[] {
                                                "Date", "Type", "Title", "Amount"
                                }));
                expenseTable.setShowGrid(true);
                jScrollPane1.setViewportView(expenseTable);

                searchDate.setBackground(new java.awt.Color(0, 0, 102));
                searchDate.setForeground(new java.awt.Color(255, 255, 255));
                searchDate.setText("Search");
                searchDate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                searchDateActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
                jPanel6.setLayout(jPanel6Layout);
                jPanel6Layout.setHorizontalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout
                                                                .createSequentialGroup()
                                                                .addComponent(jLabel10,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addGap(34, 34, 34))
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addGap(35, 35, 35)
                                                                .addComponent(jLabel15)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(fromDateChooser,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                124,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel16)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(toDateChooser,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                122,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(60, 60, 60)
                                                                .addComponent(searchDate)
                                                                .addContainerGap(214, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                jPanel6Layout.createSequentialGroup()
                                                                                .addContainerGap()
                                                                                .addComponent(jScrollPane1)
                                                                                .addContainerGap()));
                jPanel6Layout.setVerticalGroup(
                                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel6Layout.createSequentialGroup()
                                                                .addComponent(jLabel10)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel6Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel15)
                                                                                .addComponent(fromDateChooser,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(toDateChooser,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel16)
                                                                                .addComponent(searchDate))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

                jLabel12.setText("Total Income:");

                jLabel13.setText("Total Expense:");

                jLabel14.setText("Balance:");

                totalExpense.setEditable(false);
                totalExpense.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                totalExpenseActionPerformed(evt);
                        }
                });

                totalncome.setEditable(false);
                totalncome.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                totalncomeActionPerformed(evt);
                        }
                });

                balance.setEditable(false);
                balance.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                balanceActionPerformed(evt);
                        }
                });

                jLabel18.setBackground(new java.awt.Color(0, 0, 51));
                jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
                jLabel18.setForeground(new java.awt.Color(0, 0, 102));
                jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel18.setText("Summary");

                jButton1.setBackground(new java.awt.Color(255, 0, 51));
                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setText("Clear All Income And Expense");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
                jPanel7.setLayout(jPanel7Layout);
                jPanel7Layout.setHorizontalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addGroup(jPanel7Layout
                                                                                .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                false)
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel7Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel13)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(totalExpense,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                189,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel7Layout.createSequentialGroup()
                                                                                                                .addComponent(jLabel12)
                                                                                                                .addGap(26, 26, 26)
                                                                                                                .addComponent(totalncome,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                189,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                jPanel7Layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(jLabel14)
                                                                                                                .addPreferredGap(
                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)
                                                                                                                .addComponent(balance,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                189,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addContainerGap(22, Short.MAX_VALUE))
                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel18,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addContainerGap())
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                225,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                jPanel7Layout.setVerticalGroup(
                                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel7Layout.createSequentialGroup()
                                                                .addComponent(jLabel18)
                                                                .addGap(20, 20, 20)
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel12)
                                                                                .addComponent(totalncome,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(6, 6, 6)
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel13)
                                                                                .addComponent(totalExpense,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(jPanel7Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel14)
                                                                                .addComponent(balance,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                41,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jButton1)
                                                                .addGap(36, 36, 36)));

                javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                jPanel5.setLayout(jPanel5Layout);
                jPanel5Layout.setHorizontalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel5Layout
                                                                                                .createSequentialGroup()
                                                                                                .addContainerGap()
                                                                                                .addGroup(jPanel5Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(jPanel5Layout
                                                                                                                                .createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                .addGroup(jPanel5Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addComponent(jLabel6)
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(expenseTitle))
                                                                                                                                .addGroup(jPanel5Layout
                                                                                                                                                .createSequentialGroup()
                                                                                                                                                .addGroup(jPanel5Layout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addComponent(jLabel7)
                                                                                                                                                                .addComponent(jLabel11)
                                                                                                                                                                .addComponent(jLabel17))
                                                                                                                                                .addPreferredGap(
                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addGroup(jPanel5Layout
                                                                                                                                                                .createParallelGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                                .addComponent(expenseAmount)
                                                                                                                                                                .addComponent(expenseDate,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addComponent(expenseType,
                                                                                                                                                                                0,
                                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                .addGroup(
                                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                                                                jPanel5Layout
                                                                                                                                                                                                .createSequentialGroup()
                                                                                                                                                                                                .addGap(0, 124,
                                                                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                clearExpense)
                                                                                                                                                                                                .addPreferredGap(
                                                                                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                                                                                                                .addComponent(
                                                                                                                                                                                                                addExpense)))))
                                                                                                                .addComponent(jLabel5,
                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                Short.MAX_VALUE)))
                                                                                .addGroup(jPanel5Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(20, 20, 20)
                                                                                                .addComponent(jPanel7,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));
                jPanel5Layout.setVerticalGroup(
                                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(32, 32, 32)
                                                                .addGroup(jPanel5Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel5Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel5)
                                                                                                .addGap(35, 35, 35)
                                                                                                .addGroup(jPanel5Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel6)
                                                                                                                .addComponent(expenseTitle,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel5Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(jLabel7)
                                                                                                                .addComponent(expenseAmount,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addGroup(jPanel5Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(jLabel11)
                                                                                                                .addComponent(expenseDate,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(22, 22, 22)
                                                                                                .addGroup(jPanel5Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(expenseType,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel17))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addGroup(jPanel5Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(addExpense)
                                                                                                                .addComponent(clearExpense))
                                                                                                .addGap(46, 46, 46)
                                                                                                .addComponent(jPanel7,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(jPanel6,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));

                jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("Income and expenditure Application");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 19, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(jPanel5,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                538,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void clearExpenseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_clearExpenseActionPerformed
                // TODO add your handling code here:
                expenseTitle.setText("");
                expenseAmount.setText("");
                expenseDate.setDate(null);
        }// GEN-LAST:event_clearExpenseActionPerformed

        private void expenseAmountActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_expenseAmountActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_expenseAmountActionPerformed

        private void addExpenseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addExpenseActionPerformed
                // TODO add your handling code here:
                // Retrieve values from the expense form
                String title = expenseTitle.getText();
                Date date = expenseDate.getDate(); // Assuming expenseDate is a JDateChooser component
                String type = (String) expenseType.getSelectedItem();

                // Validate input
                if (title.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "Please enter a title for the expense.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }
                if (date == null) {
                        JOptionPane.showMessageDialog(this, "Please select a date for the expense.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }

                double amount;
                try {
                        amount = Double.parseDouble(expenseAmount.getText());
                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this, "Please enter a valid amount for the expense.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }

                if (amount <= 0) {
                        JOptionPane.showMessageDialog(this, "Please enter a valid amount for the expense.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }

                // Create Expense object
                ExpenseIncome expense = new ExpenseIncome(date, title, amount, type);
                String filename = "expenses.json";
                List<ExpenseIncome> expensesList = new ArrayList<>();
                expensesList.add(expense);

                try {
                        ExpenseJsonWriter.writeExpensesToJson(expensesList, filename);
                        System.out.println("Expenses written to " + filename);
                        JOptionPane.showMessageDialog(this, "Expense added successfully.", "Success",
                                        JOptionPane.INFORMATION_MESSAGE);
                } catch (IOException e) {
                        System.err.println("Error writing expenses to JSON file: " + e.getMessage());
                        JOptionPane.showMessageDialog(this, "An Error Occured.", "Error", JOptionPane.ERROR_MESSAGE);
                }
                // Clear input fields after adding expense
                expenseTitle.setText("");
                expenseAmount.setText("");
                expenseDate.setDate(null);
                DefaultTableModel model = (DefaultTableModel) expenseTable.getModel();

                // Clear existing table data
                model.setRowCount(0);

                try {
                        // Read expenses from JSON file
                        List<ExpenseIncome> expenses = ExpenseJsonReader.readExpensesFromJson("expenses.json");

                        // Populate table with expense data
                        for (ExpenseIncome expenseList : expenses) {
                                Object[] rowData = {
                                                dateFormat.format(expenseList.getDate()),
                                                expenseList.getType(),
                                                expenseList.getTitle(),
                                                expenseList.getAmount()
                                };
                                model.addRow(rowData);
                        }
                } catch (IOException e) {
                        // Handle file reading error
                        e.printStackTrace();
                }

                setExpenseTotalText();
        }// GEN-LAST:event_addExpenseActionPerformed

        private void totalncomeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_totalncomeActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_totalncomeActionPerformed

        private void totalExpenseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_totalExpenseActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_totalExpenseActionPerformed

        private void balanceActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_balanceActionPerformed
                // TODO add your handling code here:

        }// GEN-LAST:event_balanceActionPerformed

        private void searchDateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchDateActionPerformed
                // TODO add your handling code here:
                // Retrieve the selected dates
                // Retrieve selected dates
                Date fromDate = fromDateChooser.getDate();
                Date toDate = toDateChooser.getDate();

                // Ensure both dates are selected
                if (fromDate == null || toDate == null) {
                        JOptionPane.showMessageDialog(this, "Please select both From and To dates.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }

                // Ensure From date is before To date
                if (fromDate.after(toDate)) {
                        JOptionPane.showMessageDialog(this, "From Date should be before To Date.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }

                // Clear existing table data
                DefaultTableModel model = (DefaultTableModel) expenseTable.getModel();
                model.setRowCount(0);

                try {
                        // Read expenses from JSON file
                        List<ExpenseIncome> expenses = ExpenseJsonReader.readExpensesFromJson("expenses.json");

                        // Populate table with expense data within the selected date range
                        for (ExpenseIncome expense : expenses) {
                                Date expenseDate = expense.getDate();

                                // Check if expense date is within the selected range
                                if (!expenseDate.before(fromDate) && !expenseDate.after(toDate)) {
                                        Object[] rowData = {
                                                        dateFormat.format(expenseDate),
                                                        expense.getType(),
                                                        expense.getTitle(),
                                                        expense.getAmount()
                                        };
                                        model.addRow(rowData);
                                }
                        }
                } catch (IOException e) {
                        // Handle file reading error
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Error reading expenses from JSON file.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                }
        }// GEN-LAST:event_searchDateActionPerformed

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
                // Display a confirmation dialog
                int option = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete all transactions?",
                                "Confirmation", JOptionPane.YES_NO_OPTION);

                // Check the user's response
                if (option == JOptionPane.YES_OPTION) {
                        // User confirmed, proceed with clearing transactions
                        clearTransactions();
                } else {
                        // User canceled, do nothing
                        System.out.println("Clearing transactions canceled.");
                }
        }

        private void clearTransactions() {
                // Clear the contents of the JSON file
                try {
                        // Clear the file by writing an empty JSON array "[]"
                        Files.write(Paths.get("expenses.json"), "[]".getBytes());
                        System.out.println("Expenses cleared from the file.");
                } catch (IOException e) {
                        // Handle file writing error
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Error clearing expenses from JSON file.", "Error",
                                        JOptionPane.ERROR_MESSAGE);
                        return;
                }

                // Clear the JTable displaying the expenses
                DefaultTableModel model = (DefaultTableModel) expenseTable.getModel();
                model.setRowCount(0);

                // Reset the text of the JTextField components
                totalExpense.setText("0.00");
                totalncome.setText("0.00");
                balance.setText("0.00");

                JOptionPane.showMessageDialog(this, "Expenses cleared successfully.", "Success",
                                JOptionPane.INFORMATION_MESSAGE); // TODO add your handling code here:
        }// GEN-LAST:event_jButton1ActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(expense_form.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(expense_form.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(expense_form.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(expense_form.class.getName()).log(
                                        java.util.logging.Level.SEVERE, null,
                                        ex);
                }

                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new expense_form().setVisible(true);
                        }
                });

        }

        public void setExpenseTableModel(javax.swing.table.TableModel model) {
                expenseTable.setModel(model);
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton addExpense;
        private javax.swing.JTextField balance;
        private javax.swing.JButton clearExpense;
        private javax.swing.JTextField expenseAmount;
        private com.toedter.calendar.JDateChooser expenseDate;
        private javax.swing.JTable expenseTable;
        private javax.swing.JTextField expenseTitle;
        private javax.swing.JComboBox<String> expenseType;
        private com.toedter.calendar.JDateChooser fromDateChooser;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JLabel jLabel13;
        private javax.swing.JLabel jLabel14;
        private javax.swing.JLabel jLabel15;
        private javax.swing.JLabel jLabel16;
        private javax.swing.JLabel jLabel17;
        private javax.swing.JLabel jLabel18;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JPanel jPanel6;
        private javax.swing.JPanel jPanel7;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JButton searchDate;
        private com.toedter.calendar.JDateChooser toDateChooser;
        private javax.swing.JTextField totalExpense;
        private javax.swing.JTextField totalncome;
        // End of variables declaration//GEN-END:variables
}
